# fly.toml app configuration file generated for gunslinger on 2023-07-25T13:28:15+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gunslinger"
primary_region = "syd"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  BACKGROUND_JOBS_ENABLED = "t"
  GOMEMLIMIT = "800MiB"
  LOG_LEVEL = "INFO"

[[mounts]]
  source = "data"
  destination = "/data"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
