# Generated by Django 4.1.7 on 2023-03-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(blank=True, default="", max_length=100)),
                ("author", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EP", "Episode"),
                            ("VG", "Gaming"),
                            ("MN", "Manga"),
                            ("MV", "Movie"),
                            ("TR", "Track"),
                        ],
                        max_length=2,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[("AL", "Anilist"), ("PL", "Plex"), ("ST", "Steam")],
                        max_length=2,
                    ),
                ),
                ("image", models.CharField(blank=True, default="", max_length=150)),
            ],
            options={
                "ordering": ["created"],
            },
        ),
    ]
