name: Deploy to fly.io
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy gunslinger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image and push to ghcr.io
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: superfly/flyctl-actions@v1.4
        with:
          args: "deploy"
