name: Deploy to fly.io
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy gunslinger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/marcus-crane/gunslinger:latest
            ghcr.io/marcus-crane/gunslinger:${{ steps.slug.outputs.sha7 }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: "flyctl deploy"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}