name: Deploy to fly.io
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy gunslinger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # clone go-librespot into jobs directory

      - uses: superfly/flyctl-actions@v1.4
        with:
          args: "deploy"