name: "Run tests"
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # clone go-librespot into jobs directory
      # gross but go-librespot depends on them
      - name: Ubuntu dependencies
        run: sudo apt-get update && sudo apt-get install -y portaudio vorbis ogg
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - run: go mod download
      - run: go test ./...