name: "Run tests"
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # go-librespot dependencies
      - name: Ubuntu dependencies
        run: sudo apt-get update && sudo apt-get install -y libvorbis-dev libogg-dev
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - run: go mod download
      - run: go test ./...